Repository SOEN341Project/instantgram.github.io, pull requests merged in 2021-03, with the labels that each got.

#113 fixed frontend and backend session communication
  api/app.js
  api/routes/dashboard.js
  api/routes/login.js
  api/routes/profile.js
  api/views/profile.jade
  front-end/src/App.jsx
  front-end/src/components/Login/Login.jsx
Labels: bug

#115 Implemented Follow for Backend
  api/app.js
  api/data_access_layer/followDAO.js
  api/routes/follow.js
  api/routes/profile.js
  api/service_layer/followService.js
  api/views/follow.jade
Labels: enhancement

#116 Changed the pic description for picture posting
  api/data_access_layer/picsDAO.js
  api/routes/PicsController.js
  api/service_layer/PicsService.js
Labels: enhancement

#121 Created unit tests for CI #106
  api/package.json
  api/routes/usersController.js
  api/service_layer/RegistrationService.js
  api/test/test.js
  package-lock.json
Labels: enhancement

#122 #112-comments-section-improved
  front-end/src/components/Photo/Comments.css
  front-end/src/components/Photo/Comments.jsx
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
Labels: enhancement

#124 changed method from get to post for profile and logout
  api/routes/logout.js
  api/routes/profile.js
Labels: bug

#125 added mocha to backend
  api/package-lock.json
  api/package.json
Labels: enhancement

#126 #114-Connect-User-Session-and-Logout
  front-end/src/App.jsx
  front-end/src/components/Login/Login.jsx
  front-end/src/components/Navigation/Navigation.jsx
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
  front-end/src/components/Registration/Registration.jsx
Labels: enhancement

#127 added chai and supertest to backend
  api/package-lock.json
  api/package.json
Labels: enhancement

#130 #112-improved-comments-css
  front-end/src/components/Photo/Comments.css
  front-end/src/components/Photo/Comments.jsx
  front-end/src/components/Photo/Photo.css
Labels: bug

#132 #123-Restructured-the-profile-and-login Closes #123
  api/app.js
  api/images/23f747692505d1ae20029a0786d5314b
  api/images/a3eb3e7c42f41a46ccfcb1095aea358a
  api/routes/RegistrationController.js
  api/routes/login.js
  api/routes/profile.js
  api/service_layer/LoginService.js
  api/service_layer/PicsService.js
  api/service_layer/ProfileService.js
  api/service_layer/RegistrationService.js
Labels: enhancement

#134 added method to send all usernames
  api/routes/profile.js
  api/service_layer/ProfileService.js
Labels: enhancement

#135 #112-sent-comment-info-to-be
  front-end/src/components/Photo/Comments.jsx
  front-end/src/components/Photo/Photo.jsx
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
Labels: enhancement

#138 #137-implemented-following-feature
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
Labels: enhancement

#139 #133-Display-User-Profile
  api/app.js
  api/routes/allUsers.js
  front-end/src/App.jsx
  front-end/src/components/FollowerDisplay/FollowerDisplay.css
  front-end/src/components/FollowerDisplay/FollowerDisplay.jsx
  front-end/src/components/Login/Login.jsx
  front-end/src/components/Navigation/Navigation.css
  front-end/src/components/Navigation/Navigation.jsx
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
  front-end/src/components/ProfileDetails/ProfileDetails.jsx
Labels: enhancement

#140 #112-retrieved-comment-info
  front-end/src/components/Photo/Comments.jsx
  front-end/src/components/Photo/Photo.jsx
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
Labels: bug, enhancement
