Repository SOEN341Project/instantgram.github.io, pull requests merged in 2021-02, with the labels that each got.

#12 #10-Describe-Front-End-Languages-Techniques
  README.md
Labels: documentation

#22 Feature/describe project
  README.md
Labels: documentation

#20 Modified README.md to include the objective
  README.md
Labels: documentation

#17 #16-Add-Team-Member-Name-Antonio
  README.md
Labels: documentation

#25 Update READEME.md with Name - Justin
  README.md
Labels: documentation

#18 adding the Back-End Lang and Tech to READEME.md #9
  README.md
Labels: documentation

#28 #16 Added my name to the Team Members
  README.md
Labels: documentation

#23 adding my name to README.md (Bozhidar)
  README.md
Labels: documentation

#29 Reformatted the structure and font of README.md
  README.md
Labels: documentation

#34 #33-Adjust-Languages-and-Techniques-Sub-Headers
  README.md
Labels: documentation

#42 #41-Generate-Basic-React-Structure
  front-end/.gitignore
  front-end/README.md
  front-end/package-lock.json
  front-end/package.json
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/App.test.js
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/logo.svg
  front-end/src/reportWebVitals.js
  front-end/src/setupTests.js
Labels: enhancement

#45 #44-Remove-Add-Files-Folders-In-Front-End-Folder
  front-end/package-lock.json
  front-end/package.json
  front-end/public/index.html
  front-end/public/manifest.json
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/App.jsx
  front-end/src/App.test.js
  front-end/src/index.js
  front-end/src/index.jsx
  front-end/src/logo.svg
  front-end/src/reportWebVitals.js
  front-end/src/setupTests.js
Labels: enhancement

#47 #46-Implement-Layout-and-Start-NavBar-Component
  front-end/src/App.jsx
  front-end/src/components/NavBar/NavBar.css
  front-end/src/components/NavBar/NavBar.jsx
  front-end/src/components/NavBar/NavItem.jsx
  front-end/src/index.css
Labels: enhancement

#51 #50-Add-Basic-Component-Folders
  front-end/src/components/Button/Button.jsx
  front-end/src/components/FooterNav/FooterNav.jsx
  front-end/src/components/Icon/Icon.jsx
  front-end/src/components/Logo/Logo.jsx
  front-end/src/components/Photo/Photo.jsx
  front-end/src/components/PhotoGallary/PhotoGallary.jsx
  front-end/src/components/Post/Post.jsx
  front-end/src/components/Post/PostFooter/PostFooter.jsx
  front-end/src/components/Post/PostHeader/PostHeader.jsx
  front-end/src/components/ProfileArea/ProfileArea.jsx
  front-end/src/components/ProfileDetails/ProfileDetails.jsx
  front-end/src/components/ProfilePhoto/ProfilePhoto.jsx
  front-end/src/components/SearchBar/SearchBar.jsx
Labels: enhancement

#53 #52-Implemented-Navigation-Bar-Component
  front-end/src/App.jsx
  front-end/src/components/Icon/Icon.jsx
  front-end/src/components/Icons/Icons.jsx
  front-end/src/components/NavBar/NavBar.css
  front-end/src/components/NavBar/NavBar.jsx
  front-end/src/components/NavBar/NavItem.jsx
  front-end/src/components/Navigation/Navigation.css
  front-end/src/components/Navigation/Navigation.jsx
  front-end/src/index.css
  front-end/src/index.jsx
Labels: enhancement

#66 #65-Implemented-Profile-Page-Header
  front-end/src/components/ProfileDetails/ProfileDetails.css
  front-end/src/components/ProfileDetails/ProfileDetails.jsx
Labels: enhancement

#69 #48-implement-photo-header
  front-end/src/components/Photo/Photo.css
  front-end/src/components/Photo/Photo.jsx
Labels: enhancement

#70 #64-Implemented-Photo-Gallery
  front-end/src/App.jsx
  front-end/src/components/PhotoGallary/PhotoGallary.jsx
  front-end/src/components/PhotoGallery/PhotoGallery.css
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
Labels: enhancement

#74 #73-Implemented-Post-Feature-and-Fixed-Navigation
  front-end/src/App.jsx
  front-end/src/components/Icons/Icons.jsx
  front-end/src/components/Icons/logo.png
  front-end/src/components/Navigation/Navigation.css
  front-end/src/components/Navigation/Navigation.jsx
  front-end/src/components/Post/Post.css
  front-end/src/components/Post/Post.jsx
Labels: enhancement

#75 #71-implemented-photo-footer
  front-end/src/components/Photo/Photo.css
  front-end/src/components/Photo/Photo.jsx
Labels: enhancement

#81 #78-Fixed-Profile-Header
  front-end/src/App.jsx
  front-end/src/components/ProfileDetails/ProfileDetails.css
  front-end/src/components/ProfileDetails/ProfileDetails.jsx
Labels: bug

#83 #82-Implemented-Login-Page
  front-end/src/components/Login/Login.css
  front-end/src/components/Login/Login.jsx
Labels: enhancement

#79 #72-implemented-registration-form
  front-end/src/components/Forms/RegistrationForm.jsx
Labels: enhancement

#84 #77-Started-linking-post-component-to-back-end
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/components/Post/Post.jsx
  front-end/src/components/Users/Users.jsx
Labels: enhancement

#80 #26-A-user-is-now-able-to-post-and-retrieve-pictures
  api/app.js
  api/bin/www
  api/data_access_layer/picsDAO.js
  api/images/33777044835e5f8c5011d001954cf47e
  api/images/bf665671a978a95e850b4de2dc40f3f2
  api/package-lock.json
  api/routes/PicsController.js
  api/service_layer/PicsService.js
Labels: enhancement

#89 #85-Started-to-Fix-Photo-Upload
  front-end/src/App.jsx
  front-end/src/components/Post/Post.css
  front-end/src/components/Post/Post.jsx
  front-end/src/components/Post/Post2.jsx
Labels: bug

#91 #60 - Moddified registration controller to support username and password
  api/app.js
  api/data_access_layer/usersDAO.js
  api/routes/usersController.js
  api/views/register.jade
Labels: enhancement

#92 #26-Added-comment-posting-to-a-picture
  api/app.js
  api/data_access_layer/picsDAO.js
  api/routes/PicsController.js
  api/service_layer/PicsService.js
Labels: enhancement

#94 Added login with session, dashboard to verify, and logout
  api/app.js
  api/package-lock.json
  api/package.json
  api/routes/dashboard.js
  api/routes/login.js
  api/routes/logout.js
  api/views/login.jade
Labels: enhancement

#97 #96-Started-Connecting-Photo-Gallery-to-Back-End
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
  front-end/src/components/Post/Post.jsx
Labels: bug

#98 #95-Fixed-Login-Component
  front-end/src/components/Login/Login.css
  front-end/src/components/Login/Login.jsx
Labels: bug

#100 rechanged the format of the get response for get pictures
  api/images/5c39158bb20b02847fdc5f57b6b70d90
  api/routes/PicsController.js
  api/service_layer/PicsService.js
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
Labels: bug

#104 Added handling for picture posting and getting.
  api/images/095bf0b7c002f3c70b3b82d1ab8b1e58
  api/images/1eaf28488465212c31477843740899d9
  api/images/4dcb830fd982cd3628ed9e5e647e80b1
  api/images/7937ed0c14fec0932b5d649710a2c0bc
  api/images/7c8059c0331deaf830553b4cdd8aa485
  api/images/9a0f3ad3cdd7a8275282afca50959106
  api/images/c689af01f0a33eaac08186e2101c2cfa
  api/images/cba9b9ff87a1985cda79b263b30cc569
  api/images/d84500e12175fef85f1d4adfa180c98c
  api/images/f0f4031854c78b871c673cd70eac8e9a
  api/routes/PicsController.js
  api/service_layer/PicsService.js
Labels: bug

#105 #96-PhotoGallery-get-Backend
  front-end/src/App.jsx
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
Labels: bug

#102 #93-added-photo-comments
  front-end/src/components/Photo/Comments.css
  front-end/src/components/Photo/Comments.jsx
  front-end/src/components/Photo/Photo.jsx
Labels: enhancement

#107 #106 - Created .github folder & test file for CI workflow (back-end)
  api/.github/workflows/nodejs.yml
Labels: enhancement

#109 Added profile to return username of current session
  api/app.js
  api/routes/profile.js
  api/views/profile.jade
Labels: enhancement

#111 #110-Fix-User-and-Popup-Photo
  front-end/src/App.jsx
  front-end/src/components/Login/Login.jsx
  front-end/src/components/Photo/Comments.css
  front-end/src/components/Photo/Photo.css
  front-end/src/components/Photo/Photo.jsx
  front-end/src/components/Photo/Photo2.css
  front-end/src/components/Photo/Photo2.jsx
  front-end/src/components/PhotoGallery/PhotoGallery.jsx
Labels: bug
